/*
 * File: app/view/UserGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.UserGridPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.usergridpanel',

    id: 'usergridpanel',
    autoScroll: true,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    collapsible: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    id: 'top',
                    tpl: [
                        'Text: {text}<br>',
                        'ID: <a href="{text}" target="_blank">{id}</a><br> ',
                        'Cls: {cls}<br>',
                        'Is Leaf: {leaf}<br>'
                    ],
                    title: 'Top Panel',
                    flex: 1
                },
                {
                    xtype: 'gridpanel',
                    id: 'grid',
                    title: 'My xml Grid Panel',
                    store: 'XmlStore',
                    flex: 1,
                    viewConfig: {

                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'id',
                            text: 'Id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'email',
                            text: 'Email'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    id: 'bottom',
                    tpl: [
                        'Label: {label}<br>',
                        'Type: <a href="{type}" target="_blank">{type}</a><br> ',
                        'VersionID: {versionid}<br>'
                    ],
                    title: 'Bottom Panel',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});