/*
 * File: app/store/UserTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.GUSJsonStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.MyGUSJsonModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'GUSJsonStore',
            model: 'MyApp.model.MyGUSJsonModel',
            proxy: {
                type: 'ajax',
//                url: 'data/gus.json',
                url: 'data/mycars.json',
                reader: {
                    type: 'json',
//                    root: 'users'
                    root: 'data'
                }
            },
            listeners: {
                write: {
                    fn: me.onJsonpstoreWrite,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonpstoreWrite: function(store, operation, options) {

    }

});