/*
 * File: app/store/GUSXmlTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.GUSXmlTreeStore', {
    extend: 'Ext.data.TreeStore',
    requires: [
        'MyApp.model.GUSJsonTreeModel'
//        ,
//        'MyApp.overrides.CustomJsonReader'
//        ,
//        'MyApp.overrides.CustomTreeStore' // not good, coz enable this will trigger global TreeStore override
    ],

//    config: {
//        gjsonData: function(){
//            var url = 'http://localhost/js/myExtJSPrjGit/UITestBed/data/gus_qa001.xml' ;
//            var xml = new JKL.ParseXML( url, null );
//
//            var gjsonData = xml.parse();
//            return   gjsonData;
//        }
//    },

    constructor: function(cfg) {
        var me = this;


        me.gjsonData = me.initXmlTree();
//        me.initConfig(cfg);

        cfg = cfg || {};
        me.callParent([Ext.apply({

            autoLoad: true,
            storeId: 'GUSXmlTreeStore',
            model: 'MyApp.model.GUSJsonTreeModel',
            root: {
                name: 'People',
                label: 'People',
                nodeid: 'root_nodeid',
                expanded: true
            } ,
            proxy: {
//                type: 'ajax',
//                url: 'data/gus_org.xml',
//                url: 'data/gus_full.xml',
//                url: 'data/gus_qa001.xml',
                type: 'memory',
                data: me.gjsonData,
                reader: {
                    type: 'json',
                    root: function(o) {
                        if (o.explorer) { //root
                            return o.explorer.node;     // for treegrid_nested_json2.json
                        } else {
                            return o.node; // for    treegrid_nested_json.json
                        }
                    }
                }
            },
            listeners:{
                beforeexpand: {
                    fn: me.onXmltreestoreBeforeExpand,
                    scope: me
                },
                expand:{
                    fn: me.onXmltreestoreExpand,
                    scope: me
                },
                append:{
                    fn: me.onXmltreestoreAppend,
                    scope:me
                },
                load:{
                    fn:me.onXmltreestoreLoad,
                    scope:me
                }
            }
        }, cfg)]);


    },

    initXmlTree:function(){
//        var url = 'http://localhost/js/myExtJSPrjGit/UITestBed/data/gus_qa001.xml' ;
        var url = 'data/gus_qa001.xml' ;
        var xml = new JKL.ParseXML( url, null );

        var gjsonData = xml.parse();
        return   gjsonData;
    },

    onXmltreestoreBeforeExpand: function(treestore, options) {
        console.log("onXmltreestoreBeforeExpand()" + " :  treestore.data.label = " + treestore.data.label);
    },
    onXmltreestoreExpand: function(treestore, options) {
        console.log("onXmltreestoreExpand()" + " :  treestore.data.label = " + treestore.data.label);
    },
    // Each demo.UserModel instance will be automatically
    // decorated with methods/properties of Ext.data.NodeInterface
    // (i.e., a "node"). Whenever a UserModel node is appended
    // to the tree, this TreeStore will fire an "append" event.
    // http://jsfiddle.net/QvaMG/195/
    onXmltreestoreAppend: function( thisNode, newChildNode, index, eOpts ) {
    },
    onXmltreestoreLoad:function(thisNode,node,records,successful,eOpts){
        console.log("onXmltreestoreLoad");
    }
});