/*
 * File: app/store/NodesXmlTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.NodesXmlTreeStore', {
    extend: 'Ext.data.TreeStore',
    requires: [
        'MyApp.model.NodeXmlModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            storeId: 'NodesXmlTreeStore',
            model: 'MyApp.model.NodeXmlModel',
            root: {
                text: 'Ext JS',
                id: 'src',
                expanded: true
            },
            proxy: {
                type: 'ajax',
//                url: 'data/nodes.xml',
                url: 'data/nodes_simple.xml',
                reader: {
                    type: 'xml',
                    root: 'nodes',
                    record: 'node'
                }
            },
            sorters: [
                {
                    property: 'leaf'
                },
                {
                    property: 'text'
                }
            ]
        }, cfg)]);
    }
});