/*
 * File: app/store/UserTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.UserTreeStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.MyUserModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'UserTreeStore',
            model: 'MyApp.model.MyUserModel',
            proxy: {
                type: 'jsonp',
                url: 'https://api.twitter.com/1/lists/members.json?owner_screen_name=Sencha&slug=sencha-team&skip_status=true',
                reader: {
                    type: 'json',
                    root: 'users'
                }
            },
            listeners: {
                write: {
                    fn: me.onJsonpstoreWrite,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonpstoreWrite: function(store, operation, options) {

    }

});